### ISSUE TITLE
ui 개선사항 todo

### ISSUE THREAD

**Issue by Gaeun-Kwon** [TherapEase-CEOS/TherapEase-FE#26]
## Description

필수기능 구현 후 ui 개선할 사항들을 정리해둔 이슈입니다.

## Todo

- [ ]  랜딩페이지 스크롤 애니메이션 구현
- [ ]  랜딩페이지 촛불 추가
- [ ]  모든 버튼 hover style 적용 (color,bg-color)
- [ ]  필요한 경우 제외, 모든 span user-select:none 적용
- [ ]  card 컴포넌트/버튼 올라오는 transition 적용 (hover 시)
- [ ]  버튼 등장 애니메이션 적용
- [ ]  그래프 애니메이션 ?
- [ ]  키보드 입력 감지 케이스 적용 (esc / enter)
