### ISSUE TITLE
디자인 QA 1차 - 2023.07.26 (수)

### ISSUE THREAD

**Issue by Gaeun-Kwon** [TherapEase-CEOS/TherapEase-FE#41]
## Description

- https://www.figma.com/file/5n3WwPXamrmuDzXKbiIE7T?node-id=153:199&mode=design#508992102

## Todo

- [ ] 그래프 자일리톨 15*15로 수정
- [ ] 공포, 평화 등 색깔 노란색에서 그레이2로 변경
- [ ] 왼쪽 내담자 리스트 그레이 박스 너비 수정
